### ISSUE TITLE
this.authObject is undefined

### ISSUE THREAD

**Issue by rafriki** [podio/podio-js#13]
I've followed the nodejs guide but I'm getting this error:

    // app.js

    var Podio = require('podio-js').api;
 
    var podio = new Podio({
        authType: 'server',
        clientId: '<id is here>',
        clientSecret: '<secret is here>'
    });

    podio.request('GET', '/user/status').then(function(responseData) {
        console.log(responseData);
    });

    // $ node app.js

    .../node_modules/podio-js/lib/transport.js:36
    req = req.set('Authorization', 'OAuth2 ' + this.authObject.accessToken);
                                                              ^
    TypeError: Cannot read property 'accessToken' of undefined
        at Object.module.exports._addHeaders (.../node_modules/podio-js/lib/transport.js:36:63)
    at .../node_modules/podio-js/node_modules/lodash/index.js:3327:35
    at Object.module.exports.request (.../node_modules/podio-js/lib/transport.js:185:8)
    at Object.<anonymous> (.../app.js:11:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)

**Comment by dmatteo** [comment]
@Anifacted related to the recent work on this?

**Comment by Anifacted** [comment]
@dmatteo It shouldn't be related, no.
I think that it is an missing auth error check that is causing the throw. I'll investigate and get back.

**Comment by Anifacted** [comment]
@rafriki I noticed that your code is very brief, and you skipped a couple of steps for doing the full authentication process.

Before you can start sending requests, you first need to authenticate your app with Podio (redirect the user to the page where they will grant the application access the their account).

Please refer to the following code for the 'skeleton' of server side authentication:
```javascript
var podio = new PodioJS({
  authType: 'server', 
  clientId: <your client id>, 
  clientSecret: <your client secret> 
});
var redirectURL = 'https://www.myapp.com';

// Your request handler (for example in ExpressJS)
var action = function(request, response) {
var authCode = request.query.code;
var errorCode = request.query.error;

podio.isAuthenticated().then(function() {
  // Ready to make API calls...
}).catch(function(err) {

  if (typeof authCode !== 'undefined') {
    podio.getAccessToken(authCode, redirectURL, function(err, response) {
      // make API calls here 
    }); 
  } else if (typeof errorCode !== 'undefined') {
    // a problem occured
    console.log(request.query.error_description);
  } else {
    // start authentication via link or redirect
    console.log(podio.getAuthorizationURL(redirectURL));
  }
});
```

Found in this doc: http://podio.github.io/podio-js/authentication/

And see if you can get the live example working here, so you can get a sense of the auth flow: https://github.com/podio/podio-js/tree/master/examples/server_auth

**Comment by rafriki** [comment]
@Anifacted I am trying to consume the API in order to back up some data programatically. Can I authenticate with Podio just using the client ID and Secret? I wasn't intending on having any client-side interaction at all.

**Comment by albertfdp** [comment]
@rafriki The `clientId` and `clientSecret` are used for authentication of you client, but you need to authenticate the user in some form (password, server side, client side or authenticate as an app) to be able to fetch data from a specific account.

If you want to only back up for a specific app, I'd suggest you use the `authenticateWithApp`, you can find more info here: https://developers.podio.com/authentication/app_auth
