### ISSUE TITLE
How to upload image through api?

### ISSUE THREAD

**Issue by Shrutichhatbar** [podio/podio-js#27]
This is the error I recieve:
{
"error_parameters": {},
"error_detail": null,
"error_propagate": false,
"request": {
"url": "http://api.podio.com/file/v2/",
"query_string": "",
"method": "POST"
},
"error_description": "No matching operation could be found. Missing parameters: source.",
"error": "not_found"
}

What is right way (code) to upload a file?

**Comment by albertfdp** [comment]
Hi @Shrutichhatbar, what API endpoint are you using? Here you can find more info on how to upload a file: https://developers.podio.com/doc/files/upload-file-1004361

In here, you can also find an example on how to upload a file using `podio-js`: https://github.com/podio/podio-js/blob/1f8ecfea1c7a8e54e4d1d0fd6351114093c440a4/examples/server_auth/routes/index.js#L71
