### ISSUE TITLE
Uncaught Exception Crash Node in transport.js

### ISSUE THREAD

**Issue by fisettec** [podio/podio-js#41]
This is similar to Issues#16: in some circumstance, an exception in transport.js crash our node server: 

TypeError: Cannot read property 'refreshToken' of undefined
    at Object.module.exports._onResponse (/opt/node/ssi-sejours2/node_modules/podio-js/lib/transport.js:110:145)
    at Request.callback (/opt/node/ssi-sejours2/node_modules/superagent/lib/node/index.js:797:3)
    at IncomingMessage.<anonymous> (/opt/node/ssi-sejours2/node_modules/superagent/lib/node/index.js:990:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

I'm not sure what cause the error, it seem to happen randomly; podio-js is great otherwise, work for some time, and then on the same request, bam! Dealing with this error would be easy but I can't catch it in our app. Tried using domain, but can't get it to trap the error. Promises in request call don't catch it either.

The solution that worked is to patch transport.js, line 110. Replace:
if (res && res.status === 401 && (res.body.error === 'invalid_token' || res.body.error_description === 'expired_token') && this.authObject.refreshToken) {

by:
if (res && res.status === 401 && (res.body.error === 'invalid_token' || res.body.error_description === 'expired_token') && this.authObject && this.authObject.refreshToken) {

The bug happen when this.authObject is undefined, I not sure if it is a bug in itself, but the fact that this exception is not caught is causing problems...

**Comment by dmatteo** [comment]
The `authObject` should not be undefined in the first place, but I guess networking is playing a role.

I'll dig around and see if there's something more to it, otherwise I will just safe check the authObject like you suggested.

Thanks for the heads up!
