### ISSUE TITLE
Missing image size type in getThumbnailURLForFileLink

### ISSUE THREAD

**Issue by fisettec** [podio/podio-js#42]
Hi,

the ALLOWED_SIZES array in function getThumbnailURLForFileLink (general.js) is missing the "extra_large" image size. This size is useful to use in place of the native big resolution-multi-mb pictures put in Podio by some users ;) It's good enough to save us the trouble of resizing the picture in node with the like of ImageMagick.

Suggested correction, general.js, line 12:
var ALLOWED_SIZES = ['badge', 'extra_large', 'large', 'medium', 'small', 'tiny'];

**Comment by dmatteo** [comment]
Implemented.

Thanks for the report, and sorry for the long wait.

**Comment by dmatteo** [comment]
published as 1.4.3
