### ISSUE TITLE
is authType: 'app' supported?

### ISSUE THREAD

**Issue by chhuang** [podio/podio-js#43]
Can I use 'app' as authType? 

It's not mentioned anywhere in the docs: http://podio.github.io/podio-js/authentication/

Also for the browser implementation, should `var PodioJS = require('podio-js');` be `var PodioJS = require('podio-js').api;`?

**Comment by rollermy** [comment]
@chhuang, i just set the type of authentication to server and used: 
```
podio.authenticateWithApp(app.id, app.token, function (err) {
    //code here
})
```
The function is in the library, but not in the documentation. 
@podio-js Can this be added? Along with how to deal with switching between apps?

**Comment by chhuang** [comment]
@rollermy yeh that's what I did too. I did set authType to 'app', even though I'm not sure if that makes a difference.

```
let podio = new Podio.api({ 
  authType: 'app', 
  clientId: PODIO_CLIENT_ID, 
  clientSecret: PODIO_CLIENT_SECRET
});
```

**Comment by dmatteo** [comment]
@rollermy PR are very welcome! :hint: :hint: ;)

We're struggling in maintaining the open source SDKs, and a little help on the docs would be very much appreciated :)
Related file: https://github.com/podio/podio-js/tree/gh-pages/authentication

**Comment by dmatteo** [comment]
Documentation updated with app authentication
