### ISSUE TITLE
How do i access the rate limit information?

### ISSUE THREAD

**Issue by corsacca** [podio/podio-js#52]
I'm running into rate limit issues. I want to check the rate limit before making more calls

**Comment by dmatteo** [comment]
Hi @corsacca,

You can monitor your current status by examining two HTTP headers that are returned with each request you make:
http

```
X-Rate-Limit-Limit: The ceiling for the request you just made
X-Rate-Limit-Remaining: The number of requests you have left for the current 1 hour window
```

You cannot currently see when your rate limit counter is reset. 

Source: https://developers.podio.com/index/limits
